version: '3.8'
services:
  authorization_db:
    image: postgres:16-alpine3.18
    container_name: authorization_db
    restart: always
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - authorization
volumes:
  pg:
    driver: local
networks:
  authorization:
    name: authorization_network